version: '3.8'
services:
  db-server:
    image: postgres:9.6.10
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test@123
      - POSTGRES_DB=test-db
    ports:
      - '5432:5432'
    volumes:
      - /tmp/pgdata90:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - /tmp/rabbitmq:/var/lib/rabbitmq
      - /tmp/rabbitmq:/var/log/rabbitmq
  web-server:
    image: gitorko/project90:1.0.0
    ports:
      - "8080:8080"
    links:
      - db-server
      - rabbitmq
    depends_on:
      db-server:
        condition: service_started
      rabbitmq:
        condition: service_started
